[parity]
chain = "ropsten"

[footprint]
tracing = "on"
pruning = "archive"

[network]
port = 31313

[rpc]
port = 11363
interface = "all"
apis = ["web3", "puffs", "net", "pubsub", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]

[websockets]
port = 11364
interface = "all"
apis = ["web3", "puffs", "net", "pubsub", "parity", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub"]
